name: jarkko
favicon: null
layout_spectrum: 0.1928034
typography_spectrum: 0
title: Living the life on my own terms
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050403'
    - '#FCF4E7'
    - '#9A5C1F'
    - '#ABE801'
    - '#3B3B7F'
  brandStrength: 1
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
