name: jarkko
favicon: null
layout_spectrum: 0.655917993048206
typography_spectrum: 0.38195063336752355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6082203392870724
  lightness: 0.227521862834692
  saturation: 0.1464054777752608
  rhythmicContrast: 0.5251810599584132
purpose: []
