name: jarkko
favicon: null
layout_spectrum: 0.50263
typography_spectrum: 0.00906
title: Living the life on my own terms
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#957f62'
    - '#d5a874'
    - '#f4daa5'
    - '#3a240f'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
