name: jarkko
favicon: null
layout_spectrum: 0.655917993048206
typography_spectrum: 0.38195063336752355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232f3b'
    - '#ffffff'
    - '#b9b8be'
    - '#5b595e'
    - '#681a4d'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0
purpose: []
